apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tensor-fusion.fullname" . }}-portkey-registry
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.portkey.registry.dockerconfigjson }}
